include!("enum_Status.rs");
include!("message_ArticleServiceGetArticleArgsRecv.rs");
include!("enum_ArticleServiceGetArticleResultSend.rs");
include!("message_GetArticleResponse.rs");
include!("message_ArticleServiceGetArticleArgsSend.rs");
include!("message_GetArticleRequest.rs");
include!("service_ArticleService.rs");
include!("enum_ArticleServiceGetArticleResultRecv.rs");
include!("message_Article.rs");
