//! Encode/decode helpers for the raw-bytes service implementations generated by
//! volo-build when a service is served through [`crate::server::Router`].
//!
//! The generated code must not construct the unsafe protocols itself: whether the
//! unchecked binary codec is used is decided here by volo-thrift's own
//! `unsafe-codec` feature, which is off by default.

use bytes::Bytes;
use linkedbytes::LinkedBytes;
use pilota::thrift::{
    TLengthProtocol, TMessageIdentifier, ThriftException,
    binary::TBinaryProtocol,
    compact::{TCompactInputProtocol, TCompactOutputProtocol},
};

use crate::EntryMessage;

pub fn decode_entry<Msg: EntryMessage>(
    payload: &mut Bytes,
    msg_ident: &TMessageIdentifier,
    use_compact: bool,
) -> Result<Msg, ThriftException> {
    if use_compact {
        let mut protocol = TCompactInputProtocol::new(payload);
        return Msg::decode(&mut protocol, msg_ident);
    }
    decode_binary(payload, msg_ident)
}

#[cfg(not(feature = "unsafe-codec"))]
fn decode_binary<Msg: EntryMessage>(
    payload: &mut Bytes,
    msg_ident: &TMessageIdentifier,
) -> Result<Msg, ThriftException> {
    let mut protocol = TBinaryProtocol::new(payload, true);
    Msg::decode(&mut protocol, msg_ident)
}

#[cfg(feature = "unsafe-codec")]
fn decode_binary<Msg: EntryMessage>(
    payload: &mut Bytes,
    msg_ident: &TMessageIdentifier,
) -> Result<Msg, ThriftException> {
    let mut protocol =
        unsafe { pilota::thrift::binary_unsafe::TBinaryUnsafeInputProtocol::new(payload) };
    Msg::decode(&mut protocol, msg_ident)
}

pub fn encode_entry<Msg: EntryMessage>(
    msg: &Msg,
    use_compact: bool,
) -> Result<Bytes, ThriftException> {
    let mut linked_bytes = LinkedBytes::new();
    if use_compact {
        let mut size_protocol = TCompactOutputProtocol::new((), true);
        let real_size = Msg::size(msg, &mut size_protocol);
        linked_bytes.reserve(real_size - size_protocol.zero_copy_len());
        let mut protocol = TCompactOutputProtocol::new(&mut linked_bytes, true);
        Msg::encode(msg, &mut protocol)?;
    } else {
        encode_binary(msg, &mut linked_bytes)?;
    }
    Ok(linked_bytes.into_bytes_mut().freeze())
}

#[cfg(not(feature = "unsafe-codec"))]
fn encode_binary<Msg: EntryMessage>(
    msg: &Msg,
    linked_bytes: &mut LinkedBytes,
) -> Result<(), ThriftException> {
    let mut size_protocol = TBinaryProtocol::new((), true);
    let real_size = Msg::size(msg, &mut size_protocol);
    linked_bytes.reserve(real_size - size_protocol.zero_copy_len());
    let mut protocol = TBinaryProtocol::new(linked_bytes, true);
    Msg::encode(msg, &mut protocol)
}

#[cfg(feature = "unsafe-codec")]
fn encode_binary<Msg: EntryMessage>(
    msg: &Msg,
    linked_bytes: &mut LinkedBytes,
) -> Result<(), ThriftException> {
    use bytes::BufMut;
    use pilota::thrift::TOutputProtocol;

    let mut size_protocol = TBinaryProtocol::new((), true);
    let real_size = Msg::size(msg, &mut size_protocol);
    linked_bytes.reserve(real_size - size_protocol.zero_copy_len());

    let buf = unsafe {
        let l = linked_bytes.bytes_mut().len();
        std::slice::from_raw_parts_mut(
            linked_bytes.bytes_mut().as_mut_ptr().add(l),
            linked_bytes.bytes_mut().capacity() - l,
        )
    };
    let mut protocol = unsafe {
        pilota::thrift::binary_unsafe::TBinaryUnsafeOutputProtocol::new(linked_bytes, buf, true)
    };
    Msg::encode(msg, &mut protocol)?;
    let index = protocol.index();
    unsafe {
        protocol.buf_mut().bytes_mut().advance_mut(index);
    }
    Ok(())
}
